import = ["~/.config/alacritty/themes/tokyo-night-storm.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9
blur = true
startup_mode = "Maximized"
# padding.x = 5
# padding.y = 5

[font]
size = 18
normal.family = "MesloLGS NF"



